spring:
  data:
    mongodb:
      uri: mongodb+srv://amangupta3317:guptag1212@jobListing.1dwlzyn.mongodb.net/?retryWrites=true&w=majority&appName=jobListing
      database: jobListing

#Default is 8080
server:
  port: 8098

